name: Migrate database
description: Migrates the database

inputs:
  migration-object:
    description: The Kubernetes object containing the migration job
    required: true
  kubeconfig:
    description: The kubeconfig file contents, with newlines replaced with '\n' (use a secret)
    required: true
  namespace:
    description: The namespace in the Kubernetes cluster
    required: true
  timeout:
    description: The timeout for the job
    default: 60

runs:
  using: composite
  steps:
    - name: Prepare environment
      shell: bash
      run: |
        echo "TAG=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV
        echo "DATE=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV
        echo "KUBERNETES_NAMESPACE=${{ inputs.namespace }}" >> $GITHUB_ENV

    - name: Run migrate database job
      shell: bash
      run: |
        echo -e "${{ inputs.kubeconfig }}" > kubeconfig
        echo -e "${{ inputs.migration-object }}" > migration_object

        kubectl --kubeconfig kubeconfig --namespace $KUBERNETES_NAMESPACE \
          wait --for=condition=complete -f migration_object &
        completion_pid=$!

        kubectl --kubeconfig kubeconfig --namespace $KUBERNETES_NAMESPACE \
          wait --for=condition=failed -f migration_object &
        failure_pid=$!

        wait -n $completion_pid $failure_pid
        exit $?
