name: Migrate database
description: Migrates the database

inputs:
  job-name:
    description: The name of the Kubernetes job that migrates the database
    required: true
  kubeconfig:
    description: The kubeconfig file contents, with newlines replaced with '\n' (use a secret)
    required: true
  namespace:
    description: The namespace in the Kubernetes cluster
    required: true
  timeout:
    description: The timeout for the job
    default: 600
  seed:
    description: If the database should be seeded
    default: false

runs:
  using: composite
  steps:
    - name: Run migrate database job
      shell: bash
      run: |
        echo -e "${{ inputs.kubeconfig }}" > kubeconfig

        job_name=${{ inputs.job-name }}
        timeout=${{ inputs.timeout }}
        while [ $timeout -gt 0 ]; do
          echo "Waiting for job $job_name ($timeout)..."
          kubectl --kubeconfig kubeconfig --namespace ${{ inputs.namespace }} \
            get job/$job_name
          STATUS=$(kubectl --kubeconfig kubeconfig --namespace ${{ inputs.namespace }} \
            get job/$job_name -o json 2>/dev/null | jq '.status.conditions[] | .type' 2>/dev/null)

          if [ "$STATUS" == '"Complete"' ]; then
            job_result=0
            break
          elif [ "$STATUS" == '"Failed"' ]; then
            job_result=1
            break
          fi

          sleep 1
          timeout=$(( timeout - 1 ))
        done

        if [ -z "$job_result" ]; then
          echo "Job $job_name timed out"
          exit 2
        elif [ "$job_result" -eq "1" ]; then
          echo "Job $job_name failed!"
          exit 1
        fi

        echo "Job succeeded"
