name: Migrate database
description: Migrates the database

inputs:
  database:
    description: The name of the database
    required: true
  hostname:
    description: The hostname of the database
    required: true
  port:
    description: The port of the database
    default: 5432
  username:
    description: The username with access to the database
    required: true
  password:
    description: The user's password
    required: true

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      working-directory: packages/data
      run: yarn workspaces focus

    - name: Build packages
      shell: bash
      working-directory: packages/data
      run: yarn compile

    - name: Migrate database
      working-directory: packages/data
      shell: bash
      env:
        DB_NAME: ${{ inputs.database }}
        DB_HOSTNAME: ${{ inputs.hostname }}
        DB_PORT: ${{ inputs.port }}
        DB_USERNAME: ${{ inputs.username }}
        DB_PASSWORD: ${{ inputs.password }}
      run: yarn dlx knex --knexfile src/config/knexfile.ts --env production migrate:latest
