name: Migrate database
description: Migrates the database

inputs:
  migration-object:
    description: The Kubernetes object containing the migration job
    required: true
  kubeconfig:
    description: The kubeconfig file contents, with newlines replaced with '\n' (use a secret)
    required: true
  namespace:
    description: The namespace in the Kubernetes cluster
    required: true
  timeout:
    description: The timeout for the job
    default: 60

runs:
  using: composite
  steps:
    - name: Prepare environment
      shell: bash
      run: |
        echo "TAG=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV
        echo "DATE=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV
        echo "KUBERNETES_NAMESPACE=${{ inputs.namespace }}" >> $GITHUB_ENV

    - name: Run migrate database job
      shell: bash
      run: |
        echo -e "${{ inputs.kubeconfig }}" > kubeconfig
        echo -e "${{ inputs.migration-object }}" > migration_object

        timeout=${{ inputs.timeout }}
        while [ $timeout -gt 0 ]; do
          echo "Waiting for job $job_name (timeout: $timeout)..."

          status=$(kubectl --kubeconfig kubeconfig --namespace ${{ inputs.namespace }} \
            get -f migration_object -o json 2>/dev/null | jq '.status.conditions[] | .type' 2>/dev/null)

          if [ "$status" = '"Complete"' ]; then
            echo "Job completed!"
            exit 0
          elif [ "$status" = '"Failed"' ]; then
            echo "Job failed"
            exit 1
          fi

          sleep 1
          timeout=$(( timeout - 1 ))
        done

        echo "Timeout reached"
        exit 2
