version: '3.7'

volumes:
  db-data:
    name: achievements-db
    driver: local

services:
  api:
    container_name: achievements-api
    env_file: ${API_ENV:-packages/api/.env}
    environment:
      - DB_HOSTNAME=postgres
    ports:
      - 3000:3000
    user: 1000:1000

  web:
    container_name: achievements-web
    env_file: ${WEB_ENV:-packages/web/.env}
    ports:
      - 3001:3001

  postgres:
    image: postgres:latest
    container_name: achievements-pg
    env_file: .env.defaults
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    labels:
      - 'com.etimo-achievements.postgres'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: achievements-pgadmin
    env_file: .env.defaults
    ports:
      - '8011:80'
    depends_on:
      - postgres
