apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
    app.kubernetes.io/name: achievements-web
    app.kubernetes.io/instance: achievements-web-${DATE}-${TAG}
    app.kubernetes.io/version: ${TAG}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: achievements
  annotations:
    kubernetes.io/change-cause: 'release ${RELEASE}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: achievements-web
          image: niclaslindstedt/etimo-achievements-web:${COMMIT_SHA}
          resources:
            requests:
              cpu: '10m'
              memory: '32Mi'
            limits:
              cpu: '25m'
              memory: '64Mi'
          env:
            - name: API_URL
              value: '${API_URL}'
            - name: DOMAIN
              value: '${DOMAIN}'
            - name: PORT
              value: '${WEB_PORT}'
          ports:
            - containerPort: ${WEB_PORT}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: '/'
              port: ${WEB_PORT}
            timeoutSeconds: 3
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 20
