apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: achievements-web
          image: niclaslindstedt/etimo-achievements-web:${IMAGE_TAG}
          resources:
            limits:
              cpu: '0.1'
              memory: '0.128Gi'
          env:
            - name: API_URL
              value: '${API_URL}'
            - name: PORT
              value: '${WEB_PORT}'
