apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web
    app.kubernetes.io/name: achievements-web
    app.kubernetes.io/instance: achievements-web-${DATE}-${TAG}
    app.kubernetes.io/version: ${TAG}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: achievements
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: ${WEB_PORT}
