name: Docker Build
description: Build and push an app

inputs:
  kubeconfig:
    description: The kubeconfig file contents, with newlines replaced with '\n' (use a secret)
    required: true
  object-path:
    description: The path to the Kubernetes objects (yaml files)
    default: .kubernetes
  namespace:
    description: The namespace in the Kubernetes cluster
    required: true
  cluster:
    description: The cluster that is being deployed to (staging | production)
    default: staging
  tag:
    description: The image tag to deploy (all images need to have the same tag)
    default: ${{ github.sha }}

runs:
  using: composite
  steps:
    - name: Generate Kubernetes deployment spec
      shell: bash
      env:
        IMAGE_TAG: ${{ inputs.tag }}
        KUBERNETES_NAMESPACE: ${{ inputs.namespace }}
        KUBERNETES_CLUSTER: ${{ inputs.cluster }}
      run: |
        shopt -s globstar
        :>__deploy_template
        for f in ${{ inputs.object-path }}/**/*.yml; do cat $f >> __deploy_template; echo --- >> __deploy_template; done
        envsubst '$IMAGE_TAG $KUBERNETES_NAMESPACE $KUBERNETES_CLUSTER' < __deploy_template > __deployment.yaml

    - name: Deploy to Kubernetes
      shell: bash
      env:
        KUBERNETES_NAMESPACE: ${{ inputs.namespace }}
      run: |
        echo -e "${{ inputs.kubeconfig }}" > kubeconfig
        kubectl --kubeconfig=kubeconfig --namespace $KUBERNETES_NAMESPACE \
          apply -f __deployment.yaml
