version: '3.7'

services:
  api:
    build:
      dockerfile: .docker/dockerfiles/api
      context: ../..
      target: develop
    labels:
      - 'com.etimo-achievements.monitored'
    volumes:
      - ../../packages:/app/packages

  web:
    build:
      dockerfile: .docker/dockerfiles/web
      context: ../..
      target: develop
    labels:
      - 'com.etimo-achievements.monitored'
    volumes:
      - ../../packages:/app/packages
    user: 1000:1000

  nodemon:
    build:
      dockerfile: .docker/dockerfiles/nodemon
      context: ../..
    container_name: achievements-nodemon
    user: 1000:1000
    labels:
      - 'com.etimo-achievements.monitored'
    volumes:
      - ../../packages:/app/packages
      - ../../scripts:/app/scripts
