version: '3.7'

services:
  api:
    build:
      dockerfile: .docker/dockerfiles/api
      context: ../..
      target: develop
    labels:
      - 'com.etimo-achievements.monitored'
    volumes:
      - ../../packages:/app/packages

  web:
    build:
      dockerfile: .docker/dockerfiles/web
      context: ../..
      target: develop
    labels:
      - 'com.etimo-achievements.monitored'
    volumes:
      - ../../packages:/app/packages
    user: 1000:1000

  worker:
    build:
      dockerfile: .docker/dockerfiles/worker
      context: ../..
      target: develop
    labels:
      - 'com.etimo-achievements.monitored'
    volumes:
      - ../../packages:/app/packages

  nodemon:
    build:
      dockerfile: .docker/dockerfiles/nodemon
      context: ../..
    container_name: achievements-nodemon
    user: 1000:1000
    labels:
      - 'com.etimo-achievements.monitored'
    volumes:
      - ../../packages:/app/packages
      - ../../scripts:/app/scripts

  migrate:
    build:
      dockerfile: .docker/dockerfiles/migrate
      context: ../..
    container_name: achievements-migrate
    env_file: ../../packages/api/.env
    environment:
      - DB_MAIN_PRIVATE_HOST=postgres
    user: 1000:1000
    volumes:
      - ../../packages/data/src/config:/app/src/config
      - ../../packages/data/migrations:/app/migrations
      - ../../packages/data/seeds:/app/seeds
