version: '3.7'

networks:
  achievements:
  postgres:
  unleash:
  redis:

volumes:
  db-data:
    name: achievements-db
    driver: local

services:
  api:
    container_name: achievements-api
    env_file: ../../packages/api/.env
    environment:
      - DB_MAIN_PRIVATE_HOST=postgres
      - REDIS_URL=redis://redis:6379/0
    ports:
      - 3000:3000
    user: 1000:1000
    networks:
      - achievements
      - postgres
      - unleash
      - redis

  web:
    container_name: achievements-web
    env_file: ../../packages/web/.env
    ports:
      - 3001:3001
    networks:
      - achievements

  postgres:
    image: postgres:latest
    container_name: achievements-pg
    env_file: ../../.env.defaults
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    labels:
      - 'com.etimo-achievements.postgres'
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: achievements-pgadmin
    env_file: ../../.env.defaults
    ports:
      - 8011:80
    depends_on:
      - postgres
    networks:
      - postgres

  unleash:
    image: unleashorg/unleash-server:latest
    container_name: achievements-unleash
    env_file: ../../.env.defaults
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=achievements_unleash
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - DATABASE_SSL=false
      # For documentation purposes only -- these won't affect unleash credentials:
      - UNLEASH_USER=admin
      - UNLEASH_PASSWORD=unleash4all
    ports:
      - 4242:4242
    depends_on:
      - postgres
    networks:
      - unleash
      - postgres

  redis:
    image: redis:6.2
    container_name: achievements-redis
    ports:
      - 6379:6379
    networks:
      - redis
