export enum Env {
  API_URL = 'API_URL',
  FRONTEND_URL = 'FRONTEND_URL',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRATION_SECONDS = 'JWT_EXPIRATION_SECONDS',
  COOKIE_SECRET = 'COOKIE_SECRET',
  SLACK_TOKEN = 'SLACK_TOKEN',
  SLACK_CHANNEL_HIGH = 'SLACK_CHANNEL_HIGH',
  SLACK_CHANNEL_MEDIUM = 'SLACK_CHANNEL_MEDIUM',
  SLACK_CHANNEL_LOW = 'SLACK_CHANNEL_LOW',
}
