apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
    app.kubernetes.io/name: achievements-api
    app.kubernetes.io/instance: achievements-api-${DATE}-${TAG}
    app.kubernetes.io/version: ${TAG}
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: achievements
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: ${API_PORT}
