name: Docker Build
description: Build and push an app

inputs:
  dockerfile:
    description: The Dockerfile path
    required: true
  push:
    description: Whether to push or not
    default: true
  image-name:
    description: The name of the image
    required: true
  context:
    description: The Docker context to use
    default: .
  image-suffix:
    description: What suffix to use for the image (optional!)
  tag:
    description: What tag to use for the image
    default: latest
  target:
    description: The Dockerfile target to use
    default: production
  registry:
    description: The container registry to push image to
    default: ghcr.io/etimo

runs:
  using: composite
  steps:
    - name: Set short-sha
      id: short-sha
      shell: bash
      run: echo "::set-output name=sha::$(echo ${{ github.sha }} | cut -c1-7)"

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        file: .docker/Dockerfiles/${{ inputs.dockerfile }}
        target: ${{ inputs.target }}
        push: ${{ inputs.push }}
        build-args: COMMIT_SHA=${{ github.sha }}
        tags: |
          ${{ inputs.registry }}/${{ inputs.image-name }}${{ inputs.image-suffix }}:${{ github.sha }}
          ${{ inputs.registry }}/${{ inputs.image-name }}${{ inputs.image-suffix }}:${{ inputs.tag }}
        cache-from: type=gha,scope=${{ inputs.image-name }}
        cache-to: type=gha,scope=${{ inputs.image-name }},mode=max
