name: Docker Build
description: Build and push an app

inputs:
  dockerfile:
    description: The Dockerfile path
    required: true
  push:
    description: Whether to push or not
    default: true
  image-name:
    description: The name of the image
    required: true
  context:
    description: The Docker context to use
    default: .
  image-suffix:
    description: What suffix to use for the image (optional!)
  tag:
    description: What tag to use for the image
    default: latest
  target:
    description: The Dockerfile target to use
    default: production
  registry:
    description: The container registry to push image to
    default: docker.io

runs:
  using: composite
  steps:
    - name: Set branch name
      id: branch
      shell: bash
      run: echo "::set-output name=branch-name::${GITHUB_REF##*/}"

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        file: .docker/dockerfiles/${{ inputs.dockerfile }}
        target: ${{ inputs.target }}
        push: ${{ inputs.push }}
        build-args: COMMIT_SHA="${{ github.sha }}" GIT_BRANCH="${{ steps.branch.outputs.branch-name }}"
        tags: |
          ${{ inputs.registry }}/${{ inputs.image-name }}${{ inputs.image-suffix }}:${{ github.sha }}
          ${{ inputs.registry }}/${{ inputs.image-name }}${{ inputs.image-suffix }}:${{ inputs.tag }}
        cache-from: type=gha,scope=${{ inputs.image-name }}
        cache-to: type=gha,scope=${{ inputs.image-name }},mode=max
