apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
  labels:
    hash: '${TAG}'
    app.kubernetes.io/name: achievements-migrate
    app.kubernetes.io/instance: achievements-migrate-${DATE}-${TAG}
    app.kubernetes.io/version: ${TAG}
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: achievements
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        hash: '${TAG}'
        app.kubernetes.io/part-of: achievements
    spec:
      initContainers:
        - name: achievements-migrate
          image: niclaslindstedt/etimo-achievements-migrate:${TAG}
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '100m'
              memory: '256Mi'
          envFrom:
            - secretRef:
                name: provisioned-secrets
            - configMapRef:
                name: provisioned-config
  backoffLimit: 1
