apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'le-staging-wildcard-issuer'
spec:
  rules:
    - host: '${PGADMIN_URL}'
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: pgadmin-service
                port:
                  number: 80
