name: Deploy to Heroku

on:
  push:
    branches: [master]
    paths:
      - '.github/**'
      - 'packages/**'
      - '!packages/**/*.md'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'master'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: 'Deploy to Heroku'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    environment: staging
    env:
      DEFAULT_BRANCH: master
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_REGISTRY: registry.heroku.com
    steps:
      - name: Determine branch
        id: branch
        run: |
          echo "::set-output name=checkout-branch::$DEFAULT_BRANCH"
          manual="${{ github.event.inputs.branch }}"
          [[ ! -z "$manual" ]] && echo "::set-output name=checkout-branch::$manual"
          exit 0

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'refs/heads/${{ steps.branch.outputs.checkout-branch }}'

      - name: Docker login Heroku
        uses: docker/login-action@v1
        with:
          registry: ${{ env.HEROKU_REGISTRY }}
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Docker login GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/etimo
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Setup cache
        uses: ./.github/actions/setup-cache

      - uses: danielr1996/envsubst-action@1.0.0
        env:
          COMMIT_SHA: ${{ github.sha }}
          BUILD_DATE: ${{ needs.init.outputs.date }}
        with:
          input: packages/api/src/version.json
          output: packages/api/src/version.json

      - name: Build & push base image
        uses: ./.github/actions/docker-build-push
        with:
          branch: ${{ env.DEFAULT_BRANCH }}
          dockerfile: base
          image-name: etimo-achievements/base
          target: base
          tag: latest

      - name: Build & push api image
        uses: ./.github/actions/docker-build-push
        with:
          branch: ${{ env.DEFAULT_BRANCH }}
          registry: ${{ env.HEROKU_REGISTRY }}
          dockerfile: api
          image-name: etimo-achievements/api
          image-suffix: web
          tag: latest

      - name: Deploy on Heroku
        shell: bash
        run: heroku container:release web --app etimo-achievements-staging

      - name: Migrate database
        uses: ./.github/actions/migrate-database
        with:
          database: ${{ secrets.DB_NAME }}
          hostname: ${{ secrets.DB_HOSTNAME }}
          username: ${{ secrets.DB_USERNAME }}
          password: ${{ secrets.DB_PASSWORD }}
