name: Deploy to Heroku

on:
  push:
    branches: [heroku]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      - APP_NAME=etimo-achievements-staging
      - HEROKU_EMAIL=${{ secrets.HEROKU_EMAIL }}
      - HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Image
        run: |
          docker build \
            -f .docker/Dockerfiles/api \
            -t registry.heroku.com/${{ env.APP_NAME }}/web \
            .

      - name: Push Image
        run: docker push registry.heroku.com/${{ env.APP_NAME }}/web
