name: Deploy to Staging K8S

concurrency: production_environment

on:
  push:
    branches: [kubernetes]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: 'Deploy to Staging K8S'
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push base image
        uses: ./.github/actions/docker-build-push
        with:
          registry: docker.io
          dockerfile: base
          image-name: niclaslindstedt/etimo-achievements-base
          target: base
          tag: latest

      - name: Build & push base image
        uses: ./.github/actions/docker-build-push
        with:
          registry: docker.io
          dockerfile: api
          image-name: niclaslindstedt/etimo-achievements-api
          target: production
          tag: latest

      - name: Build & push base image
        uses: ./.github/actions/docker-build-push
        with:
          registry: docker.io
          dockerfile: web
          image-name: niclaslindstedt/etimo-achievements-web
          target: production
          tag: latest
