name: Deploy to Staging K8S

concurrency: production_environment

on:
  push:
    branches: [kubernetes]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: 'Deploy to Staging K8S'
    runs-on: ubuntu-latest
    environment: staging
    env:
      KUBERNETES_NAMESPACE: achievements

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/etimo
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Setup cache
        uses: ./.github/actions/setup-cache

      - name: Build & push base image
        uses: ./.github/actions/docker-build-push
        with:
          dockerfile: base
          image-name: etimo-achievements/base
          target: base
          tag: latest

      - name: Build & push api image
        uses: ./.github/actions/docker-build-push
        with:
          registry: docker.io
          dockerfile: api
          image-name: niclaslindstedt/etimo-achievements-api
          target: production
          tag: latest

      - name: Build & push web image
        uses: ./.github/actions/docker-build-push
        with:
          registry: docker.io
          dockerfile: web
          image-name: niclaslindstedt/etimo-achievements-web
          target: production
          tag: latest

      - name: Deploy to Kubernetes
        uses: ./.github/actions/deploy-kubernetes
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: ${{ env.KUBERNETES_NAMESPACE }}
          tag: $GITHUB_SHA
