name: Run tests

concurrency: test

on:
  push:
    branches: [master]
    paths:
      - '.docker/**'
      - '.github/**'
      - 'packages/**'
      - '!packages/**/*.md'

defaults:
  run:
    shell: bash

jobs:
  test:
    name: 'Run tests'
    runs-on: ubuntu-latest
    container:
      image: node:14
    strategy:
      fail-fast: true
    env:
      NODE_ENV: development
      DB_HOSTNAME: postgres
      DB_SSL: false
      DB_NAME: root
      DB_USERNAME: root
      DB_PASSWORD: postgres

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Migrate & seed database
        uses: ./.github/actions/migrate-database
        with:
          hostname: ${{ env.DB_HOSTNAME }}
          port: ${{ job.services.postgres.ports[5432] }}
          database: ${{ env.DB_NAME }}
          username: ${{ env.DB_USERNAME }}
          password: ${{ env.DB_PASSWORD }}
          ssl: ${{ env.DB_SSL }}
          environment: ${{ env.NODE_ENV }}
          seed: true

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: npm run test

      - name: Run integration tests
        run: npm run test-integration
